# Generated by Django 5.2.4 on 2025-07-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anaylsis', 'for_pgvector'),
    ]

    operations = [
    ]
