# Generated by Django 5.2.4 on 2025-07-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anaylsis', '0002_remove_app_content_app_app_ip_app_csv_app_drivers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_ip',
            new_name='app_id',
        ),
    ]
